ARG PHP_LIB
ENV PHP_LIB ${PHP_LIB:-8}
FROM node:current-alpine3.13
RUN apk update \
    && apk add \
    bash \
    sudo \
    curl \
    git \
    openssh-client \
    tar \
    gzip \
    ca-certificates \
    zip \
    unzip \
    icu-dev \
    libmcrypt-dev \
    freetype-dev \
    libjpeg-turbo-dev \
    libpng-dev \
    netcat-openbsd \
    php${PHP_LIB} \
    php${PHP_LIB}-curl \
    php${PHP_LIB}-gd \
    php${PHP_LIB}-intl \
    php${PHP_LIB}-json \
    php${PHP_LIB}-mbstring \
    php${PHP_LIB}-opcache \
    php${PHP_LIB}-openssl \
    php${PHP_LIB}-pcntl \
    php${PHP_LIB}-xml \
    php${PHP_LIB}-mysqlnd \
    php${PHP_LIB}-phar \
    php${PHP_LIB}-mysqli \
    php${PHP_LIB}-pdo_mysql \
    php${PHP_LIB}-dom \
    php${PHP_LIB}-tokenizer \
    php${PHP_LIB}-simplexml \
    php${PHP_LIB}-xmlwriter \
    php${PHP_LIB}-fpm \
    php${PHP_LIB}-zlib \
    py3-pip \
    python3-dev \
    libffi-dev \
    openssl-dev \
    gcc \
    libc-dev \
    make \
    mariadb-client \
    nodejs \
    \
    python3 \
    git \
    make \
    g++ \
    && apk del build-base \
    && rm -rf /var/cache/apk/*
WORKDIR /var/www/html/
RUN node -v && npm -v
