ARG ALPINE_VERSION
ARG NODE_VERSION

ARG HTDOCS

# Use multi-stage build for Node.js
FROM node:${NODE_VERSION}-alpine as node-builder

ENV NODE_VERSION ${NODE_VERSION:-"18"}

ENV HTDOCS ${HTDOCS:-"/var/www/htdocs/localhost"}

RUN mkdir -p ${HTDOCS}
WORKDIR ${HTDOCS}

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile
RUN yarn && npm link balena-cloud-apps

ENV ALPINE_VERSION ${ALPINE_VERSION:-"3.15"}

FROM php:7.4.33-alpine${ALPINE_VERSION}

# Copy Node.js dependencies from builder
COPY --from=node-builder node_modules node_modules

# Add non-root user
RUN addgroup -S www-data && adduser -h ${HTDOCS} -S www-data -G www-data -u ${PUID} -D
USER www-data

# ----------------------
# About Dockerfile ARGS:
# ALL the following ARGS are DUPLICATED in common.env and $BALENA_ARCH.env
# and Scripts/fooargs.sh for development phase.
# If not set in common.env, it must be set in the host machine environment
# when ./start.sh or ./test.sh or in development phase.
# ----------------------
#                        Values in default (no-arg) production mode
#                        May be overriden in docker-compose.yml
#-----------------------
ARG CAKEPHP_DEBUG_LEVEL
ENV CAKEPHP_DEBUG_LEVEL ${CAKEPHP_DEBUG_LEVEL:-2}
ARG BALENA_MACHINE_NAME
ENV BALENA_MACHINE_NAME ${BALENA_MACHINE_NAME:-%%BALENA_MACHINE_NAME%%}
ARG SECONDARY_HUB
ENV SECONDARY_HUB ${SECONDARY_HUB:-%%SECONDARY_HUB%%}
ARG BALENA_ARCH
ENV BALENA_ARCH ${BALENA_ARCH:-%%BALENA_ARCH%%}
ARG COLLECT_COVERAGE
ENV COLLECT_COVERAGE ${COLLECT_COVERAGE:-'False'}
ARG MYPHPCMS_DIR
ENV MYPHPCMS_DIR ${MYPHPCMS_DIR:-'app/webroot/php-cms'}
ARG MYPHPCMS_LOG
ENV MYPHPCMS_LOG ${MYPHPCMS_LOG:-'app/tmp/logs'}
ARG SERVER_NAME
ENV SERVER_NAME ${SERVER_NAME:-'acake2php.local'}
# Change uid and gid of apache to docker user uid/gid
ARG PUID
ENV PUID ${PUID:-1000}
ARG PGID
ENV PGID ${PGID:-1000}
# Must own the ip address
ARG HTTP_PORT
ENV HTTP_PORT ${HTTP_PORT:-'80'}
ARG SSL_PORT
ENV SSL_PORT ${SSL_PORT:-'443'}
# Enable migrate-database.sh options
ARG MIGRATE_OPTION
ENV MIGRATE_OPTION ${MIGRATE_OPTION:-'-v'}
# Database connection
ARG DB
ENV DB ${DB:-Mysql}
ARG MYSQL_HOST
ENV MYSQL_HOST ${MYSQL_HOST:-db}
ARG MYSQL_TCP_PORT
ENV MYSQL_TCP_PORT ${MYSQL_TCP_PORT:-3306}
ARG MYSQL_DATABASE
ENV MYSQL_DATABASE ${MYSQL_DATABASE:-'aria_db'}
ARG MYSQL_ROOT_PASSWORD
ENV MYSQL_ROOT_PASSWORD ${MYSQL_ROOT_PASSWORD:-'mariadb'}
ARG TEST_MYSQL_DATABASE
ENV TEST_MYSQL_DATABASE ${TEST_MYSQL_DATABASE:-'test'}
ARG MYSQL_USER
ENV MYSQL_USER ${MYSQL_USER:-'maria'}
ARG MYSQL_PASSWORD
ENV MYSQL_PASSWORD ${MYSQL_PASSWORD:-'maria-abc'}
ARG HASH_PASSWORD
ENV HASH_PASSWORD ${HASH_PASSWORD:-'password'}
ARG HTDOCS
ENV HTDOCS /var/www/htdocs/localhost

## Install base packages
RUN apk update \
    && apk add --no-cache \
    bash \
    envsubst \
    apache2 \
    apache2-ctl \
    apache2-ssl \
    curl

RUN apk del build-base \
    && rm -rf /var/cache/apk/*

# Copy the code inside the image root
COPY . .

# COPY apache site.conf file
RUN envsubst < etc/apache2/site.conf > /etc/apache2/conf.d/000-default.conf

# COPY apache site.conf file
RUN envsubst < etc/apache2/site_ssl.conf > /etc/apache2/conf.d/001-ssl.conf

# Stream apache logs to standard outputs
RUN ln -sf /dev/stdout /var/log/apache2/access.log && \
    ln -sf /dev/stderr /var/log/apache2/error.log

# Create tmp directory and make it writable by the web server
RUN mkdir -p \
    app/tmp/cache/models \
    app/tmp/cache/persistent \
  && chown -R :www-data \
    app/tmp \
  && chmod -R 770 \
    app/tmp

RUN pecl install redis-5.3.7 \
	&& pecl install xdebug-3.2.1 \
	&& docker-php-ext-enable redis xdebug

RUN apk update \
    && apk add \
    libmemcached-dev \
    libssl-dev \
    zlib1g-dev \
	&& pecl install memcached-3.2.0 \
	&& docker-php-ext-enable memcached

RUN apk del build-base \
    && rm -rf /var/cache/apk/*

# Add cake and composer command to system path
ENV PATH "${PATH}:${HTDOCS}/app/bin"
ENV PATH "${PATH}:${HTDOCS}/bin"

RUN chmod 0755 *.sh && chmod 0755 Scripts/*.sh
# Password Hash Verbosity (MAYBE SECURITY LACK)
# RUN cat app/webroot/php-cms/e13/etc/export_hash_password.sh | awk -F= '{print $2}' | tail -n 1

# Helper packages (just a long node process...)
RUN chmod +x Scripts/*.sh 
RUN Scripts/update-templates.sh || true

# configure server variables
RUN ./configure.sh --runner -a -p ${HASH_PASSWORD} -s "$(openssl rand -hex 4)" --development

RUN printf "TO LOGIN INSIDE 'ACAKE2PHP' CONTAINER: \n"
RUN printf "docker exec -it \$(docker ps | grep acake2php | awk {'printf \$1'}) bash \n"

RUN ./migrate-database.sh -r -i -u ${MIGRATE_OPTION} \
&& ./migrate-database.sh -r -u ${MIGRATE_OPTION} --connection=test \

# Expose the ports for apache
EXPOSE 80 443

# Enable Apache modules and restart
RUN a2enmod rewrite \
  && service apache2 restart

ENTRYPOINT ["apachectl", "-D", "FOREGROUND"]
