ARG HTDOCS

# BEGIN - Multi-stage Build
# Stage 1: Install NodeJS dependencies
FROM node:22-alpine AS node-build

WORKDIR ~/project

# Copy Node.js dependency files
COPY package.json yarn.lock ./
RUN corepack enable \
    && corepack prepare yarn@stable --activate \
    && yarn install --immutable \
    && yarn cache clean

# Stage 2: Build PHP and Apache environment
FROM php:7.4.33-alpine3.15

# Set up working directory and environment
ENV HTDOCS=${HTDOCS:-"/var/www/htdocs/localhost"}
RUN mkdir -p ${HTDOCS}
WORKDIR ${HTDOCS}

COPY --from=node-build /usr/local/lib/node_modules/ node_modules
# END - Multi-stage Build

# Install base packages
RUN apk add --no-cache \
    bash gettext apache2 apache2-ctl apache2-ssl curl \
    && ln -sf /dev/stdout /var/log/apache2/access.log \
    && ln -sf /dev/stderr /var/log/apache2/error.log

# Copy application files
COPY . .

# Set up Apache configuration
RUN envsubst < etc/apache2/site.conf > /etc/apache2/conf.d/000-default.conf \
    && envsubst < etc/apache2/site_ssl.conf > /etc/apache2/conf.d/001-ssl.conf

# Set permissions for temporary directories
RUN mkdir -p app/tmp/cache/models app/tmp/cache/persistent \
    && chown -R :www-data app/tmp \
    && chmod -R 770 app/tmp

# Add mor NodeJS, CakePHP and Composer commands to system path
ENV PATH="${HTDOCS}/node_modules/.bin:${HTDOCS}/app/bin:${HTDOCS}/bin:${PATH}"

# ----------------------
# About Dockerfile ARGS:
# ALL the following ARGS are DUPLICATED in common.env and $BALENA_ARCH.env
# and Scripts/fooargs.sh for development phase.
# If not set in common.env, it must be set in the host machine environment
# when ./start.sh or ./test.sh or in development phase.
# ----------------------
#                        Values in default (no-arg) production mode
#                        May be overriden in docker-compose.yml
#-----------------------
ARG CAKEPHP_DEBUG_LEVEL
ENV CAKEPHP_DEBUG_LEVEL ${CAKEPHP_DEBUG_LEVEL:-2}
ARG BALENA_MACHINE_NAME
ENV BALENA_MACHINE_NAME ${BALENA_MACHINE_NAME:-raspberrypi3}
ARG SECONDARY_HUB
ENV SECONDARY_HUB ${SECONDARY_HUB:-%%SECONDARY_HUB%%}
ARG BALENA_ARCH
ENV BALENA_ARCH ${BALENA_ARCH:-armhf}
ARG PHP_EXTENSIONS
ENV PHP_EXTENSIONS ${PHP_EXTENSIONS:-"gd redis memcached"}
ARG COLLECT_COVERAGE
ENV COLLECT_COVERAGE ${COLLECT_COVERAGE:-'False'}
ARG MYPHPCMS_DIR
ENV MYPHPCMS_DIR ${MYPHPCMS_DIR:-'app/webroot/php-cms'}
ARG MYPHPCMS_LOG
ENV MYPHPCMS_LOG ${MYPHPCMS_LOG:-'app/tmp/logs'}
ARG SERVER_NAME
ENV SERVER_NAME ${SERVER_NAME:-'acake2php.local'}
# Change uid and gid of apache to docker user uid/gid
ARG PUID
ENV PUID ${PUID:-0}
ARG PGID
ENV PGID ${PGID:-0}
# Must own the ip address
ARG HTTP_PORT
ENV HTTP_PORT ${HTTP_PORT:-'80'}
ARG SSL_PORT
ENV SSL_PORT ${SSL_PORT:-'443'}
# Enable migrate-database.sh options
ARG MIGRATE_OPTION
ENV MIGRATE_OPTION ${MIGRATE_OPTION:-'-v'}
# Database connection
ARG DB
ENV DB ${DB:-Mysql}
ARG MYSQL_HOST
ENV MYSQL_HOST ${MYSQL_HOST:-db}
ARG MYSQL_TCP_PORT
ENV MYSQL_TCP_PORT ${MYSQL_TCP_PORT:-3306}
ARG MYSQL_DATABASE
ENV MYSQL_DATABASE ${MYSQL_DATABASE:-'aria_db'}
ARG MYSQL_ROOT_PASSWORD
ENV MYSQL_ROOT_PASSWORD ${MYSQL_ROOT_PASSWORD:-'mariadb'}
ARG TEST_MYSQL_DATABASE
ENV TEST_MYSQL_DATABASE ${TEST_MYSQL_DATABASE:-'test'}
ARG MYSQL_USER
ENV MYSQL_USER ${MYSQL_USER:-'maria'}
ARG MYSQL_PASSWORD
ENV MYSQL_PASSWORD ${MYSQL_PASSWORD:-'maria-abc'}
ARG HASH_PASSWORD
ENV HASH_PASSWORD ${HASH_PASSWORD:-'password'}

# Install necessary PHP extensions and dependencies
COPY --from=ghcr.io/mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/
RUN install-php-extensions ${PHP_EXTENSIONS}

# Run initialization scripts
RUN chmod +x Scripts/*.sh \
    && update_templates \
    && ./configure.sh --runner -a -p ${HASH_PASSWORD} -s "$(openssl rand -hex 4)" --development \
    && ./migrate-database.sh -r -i -u ${MIGRATE_OPTION} \
    && ./migrate-database.sh -r -u ${MIGRATE_OPTION} --connection=test

# Expose Apache ports
EXPOSE 80 443

# Enable Apache modules and start the server
RUN a2enmod rewrite
ENTRYPOINT ["apachectl", "-D", "FOREGROUND"]
