version: "2.1"
services:
  db:
    build:
      context: deployment/images/mysqldb
      dockerfile: Dockerfile.armhf
      args:
        PUID: 1000
        PGID: 1000
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      TZ: Europe/Paris
    volumes:
      - localtime:/etc/localtime:ro
      - db-data:/config
      - db-socket:/var/run/mysqld
    ports:
      - "3306:3306"
    restart: unless-stopped
    networks:
      - cake
    env_file:
      - common.env
      - armhf.env
    labels:
      io.balena.features.dbus: "1"
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile.armhf
      args:
        PUID: 1000
        PGID: 1000
        MYPHPCMS_DIR: app/webroot/php-cms
        MYPHPCMS_LOG: app/tmp/logs
        HTDOCS: /var/www/html
    env_file:
      - common.env
      - armhf.env
    environment:
      CAKEPHP_DEBUG_LEVEL: "2"
      COLLECT_COVERAGE: false
      CAKEPHP_SECURITY_SALT: Word
      CAKEPHP_SECURITY_CIPHER_SEED: 01234
    volumes:
      - localtime:/etc/localtime:ro
      - www:/var/www
      - etc:/usr/local/etc
    ports:
      - "9001:9001"
    networks:
      - cake
  apache:
    build:
      context: deployment/images/httpd
      dockerfile: Dockerfile.armhf
      args:
        PUID: 1000
        PGID: 1000
        HTDOCS: /var/www/html
    env_file:
      - common.env
      - armhf.env
    volumes:
      - localtime:/etc/localtime:ro
      - www:/var/www
      - apache2:/usr/local/apache2
    ports:
      - "80:80"
      - "443:443"
    networks:
      - cake
  balena-storage:
    build:
      context: balena-storage
      dockerfile: Dockerfile.armhf
    privileged: true
    env_file:
      - common.env
      - armhf.env
    networks:
      - cake
# v3.4 compose file
#    healthcheck:
#      test: ["CMD", "/usr/src/scripts/backup-db.sh"]
#      interval: 720h
#      timeout: 10s
#      retries: 3
#      start_period: 30m
    volumes:
      - db-backup:/mnt/external-drives
volumes:
  www:
  etc:
  apache2:
  hostapcache:
  db-data:
  db-socket:
  config:
  localtime:
  db-backup:
networks:
  cake:
    external: false
