# syntax=docker/dockerfile:1
ARG SECONDARY_HUB
ARG SECONDARY_TAG
FROM ${SECONDARY_HUB:-linuxserver/mariadb}:${SECONDARY_TAG:-arm32v7-10.6.13}

ARG PUID
ENV PUID=${PUID:-0}
ARG PGID
ENV PGID=${PGID:-0}
ARG MYSQL_HOST
ENV MYSQL_HOST=${MYSQL_HOST:-'localhost'}
ARG TZ
ENV TZ=${TZ:-'Europe/Paris'}
ARG MYSQL_BIND_ADDRESS
ENV MYSQL_BIND_ADDRESS=${MYSQL_BIND_ADDRESS:-0.0.0.0}
ENV BALENA_SECRETS_DIR=/run/secrets

COPY . .
COPY load-balena-secrets.sh /usr/local/bin/load-balena-secrets
COPY entrypoint.sh /usr/local/bin/mysqldb-entrypoint
RUN install -d -m 0750 /run/secrets

COPY conf.d/my.cnf /etc/my.cnf.d/my.cnf
RUN sed -i.bind "/bind-address/s/=.*$/= ${MYSQL_BIND_ADDRESS}/" /etc/my.cnf.d/my.cnf
RUN sed -i.user "/user/s/=.*$/= ${USER}/" /etc/my.cnf.d/my.cnf

RUN apk update \
    && apk upgrade \
    && apk add \
      build-base \
      expect \
      xz \
    mariadb-client \
    && apk del build-base \
    && rm -rf /var/cache/apk/*

RUN chmod 1755 mysql_secure_shell \
    && chmod 0755 /usr/local/bin/load-balena-secrets /usr/local/bin/mysqldb-entrypoint \
    && ./mysql_secure_shell

# This script runs ONCE at first container start, using runtime env vars
COPY init-db.sh /docker-entrypoint-initdb.d/init-db.sh
RUN chmod 755 /docker-entrypoint-initdb.d/init-db.sh

# Splash screen ;)
RUN cat mariadb.ans

VOLUME /var/run/mysqld
ENTRYPOINT ["/usr/local/bin/mysqldb-entrypoint"]
