ARG NODE_VERSION   
ENV NODE_VERSION ${NODE_VERSION:-"18"}
ARG ALPINE_VERSION
ENV ALPINE_VERSION ${ALPINE_VERSION:-"3.15"}

FROM php:7.4.33-fpm-alpine${ALPINE_VERSION}

ARG HTDOCS
ENV HTDOCS /var/www/htdocs/localhost

# Use the default production configuration
RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"

RUN apk update \
    && apk add \
    python3 \
    bash \
    git \
    zip \
    unzip \
    mariadb-client

RUN apk del build-base \
    && rm -rf /var/cache/apk/*

COPY php-ini-overrides.ini /etc/php/7.4.33/fpm/conf.d/99-overrides.ini

# Enable PHP extensions
COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/

RUN install-php-extensions \
    odbc \
    curl \
    gd \
    intl \
    json \
    mbstring \
    opcache \
    openssl \
    pcntl \
    xml \
    mysqlnd \
    phar \
    mysqli \
    pdo_mysql \
    dom \
    tokenizer \
    simplexml \
    xmlwriter \
    #fpm \
    zlib

# Install composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin/ --filename=composer

# php-fpm configuration install
COPY etc/php-fpm.d /etc/php-fpm.d

# mkdir localhost web server folder for apache2 itself
RUN mkdir -p ${HTDOCS}
RUN adduser -h ${HTDOCS} -s /sbin/nologin -g apache -D apache

# node JS install
COPY Scripts Scripts
RUN chmod +x Scripts/*.sh
RUN Scripts/nodejs-install.sh
RUN node -v && npm -v
