ARG ALPINE_VERSION=3.15
ARG NODE_VERSION=18

ARG HTDOCS

# Use multi-stage build for Node.js
FROM node:${NODE_VERSION}-alpine as node-builder

ENV HTDOCS ${HTDOCS:-"/var/www/htdocs/localhost"}

RUN mkdir -p ${HTDOCS}
WORKDIR ${HTDOCS}

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile
RUN yarn && npm link balena-cloud-apps

FROM php:7.4.33-fpm-alpine${ALPINE_VERSION}

# Copy Node.js dependencies from builder
COPY --from=node-builder node_modules node_modules

# Add non-root user
RUN addgroup -S www-data && adduser -h ${HTDOCS} -S www-data -G www-data -u ${PUID} -D
USER www-data

# Use the default production configuration
RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"

RUN apk update \
    && apk add --no-cache \
    python3 \
    bash \
    git \
    zip \
    unzip \
    mariadb-client

RUN apk del build-base \
    && rm -rf /var/cache/apk/*

COPY php-ini-overrides.ini /etc/php/7.4.33/fpm/conf.d/99-overrides.ini

# Enable PHP extensions
COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/

RUN install-php-extensions \
    odbc \
    curl \
    gd \
    intl \
    json \
    mbstring \
    opcache \
    openssl \
    pcntl \
    xml \
    mysqlnd \
    phar \
    mysqli \
    pdo_mysql \
    dom \
    tokenizer \
    simplexml \
    xmlwriter \
    #fpm \
    zlib

# Install composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin/ --filename=composer

# php-fpm configuration install
COPY etc/php-fpm.d /etc/php-fpm.d

# node JS install
#COPY Scripts Scripts
#RUN chmod +x Scripts/*.sh
#RUN Scripts/nodejs-install.sh

RUN node -v && npm -v
