# BEGIN - Multi-stage Build
# Stage 1: Install NodeJS dependencies
FROM node:20-alpine3.16 AS node-build

WORKDIR /usr/local/project

# Copy Node.js dependency files, Fixing global modules issue
COPY package.json yarn.lock .yarnrc.yml ./
COPY .yarn/ .yarn 
RUN apk update \
    && apk add --no-cache yarn \
    && yarn install --immutable \
    && yarn cache clean

# Stage 2: Build environment
FROM httpd:2.4-alpine3.22

# Set up working directory and environment
ARG HTDOCS
ENV HTDOCS=${HTDOCS:-"/usr/local/apache2/htdocs"}
WORKDIR ${HTDOCS}

# Add mor NodeJS, CakePHP and Composer commands to system path
COPY --from=node-build /usr/local/project/node_modules/ node_modules
ENV PATH="${HTDOCS}/node_modules/.bin:${PATH}"
# END - Multi-stage Build

# Install base packages
RUN apk add --no-cache \
    bash gettext apache2 apache2-ctl apache2-ssl curl git \
    && ln -sf /dev/stdout /var/log/apache2/access.log \
    && ln -sf /dev/stderr /var/log/apache2/error.log

# Copy application files
COPY . .

# Set up Apache configuration
RUN envsubst < etc/apache2/sites-available/000-default.conf > /etc/apache2/conf.d/000-default.conf \
    && envsubst < etc/apache2/sites-available/001-ssl.conf > /etc/apache2/conf.d/001-ssl.conf

# Expose Apache ports
EXPOSE 80 443

# Enable Apache modules and start the server
RUN chmod +x Scripts/*.sh \
    && Scripts/a2enmod.sh

ENTRYPOINT ["apachectl", "-D", "FOREGROUND"]
