# BEGIN - Multi-stage Build
# Stage 1: Install NodeJS dependencies
FROM node:20-alpine3.16 AS node-build

WORKDIR /usr/local/project

# Copy Node.js dependency files, Fixing global modules issue
RUN apk update \
    && apk add --no-cache yarn \
    && yarn add balena-cloud-apps \
    && yarn cache clean

# Stage 2: Build environment
FROM httpd:2.4-alpine3.22

# Set up working directory and environment
ARG HTDOCS
ENV HTDOCS=${HTDOCS:-"/usr/local/apache2/htdocs"}
WORKDIR ${HTDOCS}

# Add mor NodeJS, CakePHP and Composer commands to system path
COPY --from=node-build /usr/local/project/node_modules/ node_modules
ENV PATH="${HTDOCS}/node_modules/.bin:${PATH}"
# END - Multi-stage Build

# Install base packages
RUN apk update \
    && apk add --no-cache \
    bash gettext curl git

RUN apk del build-base \
    && rm -rf /var/cache/apk/*

# Copy application files
COPY . .

ARG SERVER_ROOT
ENV SERVER_ROOT=${SERVER_ROOT:-"/usr/local/apache2"}
ARG SERVER_NAME
ENV SERVER_NAME=${SERVER_NAME:-"acake2php.local"}
ARG HTTP_PORT
ENV HTTP_PORT=${HTTP_PORT:-80}
ARG SSL_PORT
ENV SSL_PORT=${SSL_PORT:-443}

# add dedicated user
RUN user=httpd group=www-data uid=1000 adduser -h $PWD -G $group -D -u $uid $user \
    && sed -i -E -e "#User#s#www-data#$user#g -e #Group#s#www-data#$group#g" "${SERVER_ROOT}/conf/httpd.conf"

# Set up Apache configuration
RUN envsubst < etc/apache2/conf-available/servername.conf > ${SERVER_ROOT}/conf/extra/servername.conf \
    && envsubst < etc/apache2/sites-available/000-default.conf > ${SERVER_ROOT}/conf/extra/000-default.conf \
    && envsubst < etc/apache2/sites-available/001-ssl.conf > ${SERVER_ROOT}/conf/extra/001-ssl.conf \
    && echo "Include extra/servername.conf" >> ${SERVER_ROOT}/conf/httpd.conf \
    && echo "Include extra/000-default.conf" >> ${SERVER_ROOT}/conf/httpd.conf \
    && echo "Include extra/001-ssl.conf" >> ${SERVER_ROOT}/conf/httpd.conf


# Expose Apache ports
EXPOSE 80 443

# Enable Apache modules and start the server
RUN chmod +x Scripts/*.sh \
    && Scripts/a2enmod.sh

ENTRYPOINT ["apachectl", "-D", "FOREGROUND"]
