# BEGIN - Multi-stage Build
# Stage 1: Install NodeJS dependencies
FROM node:20-alpine3.22 AS node-build

WORKDIR /usr/local/project

# Copy Node.js dependency files, Fixing global modules issue
COPY package.json yarn.lock .yarnrc.yml ./
COPY .yarn .yarn
RUN apk add --no-cache nodejs npm \
 && npm install -g corepack \
 && corepack enable \
 && corepack prepare yarn@4 --activate \
 && corepack install -g yarn \
 && yarn install --immutable \
 && yarn cache clean

# Stage 2: Build HTTPD environment
FROM httpd:2.4-alpine3.22

# Set up working directory and environment
ARG HTDOCS
ENV HTDOCS=${HTDOCS:-"/usr/local/apache2/htdocs"}
WORKDIR ${HTDOCS}

# Add mor NodeJS, CakePHP and Composer commands to system path
ENV PATH="${HTDOCS}/node_modules/.bin:${HTDOCS}/app/bin:${HTDOCS}/bin:${PATH}"
COPY --from=node-build /usr/local/project/node_modules node_modules
# END - Multi-stage Build

# Install base packages
RUN apk update \
    && apk add --no-cache \
    bash gettext curl git openssl

RUN apk del build-base \
    && rm -rf /var/cache/apk/*

ARG SERVER_ROOT
ENV SERVER_ROOT=${SERVER_ROOT:-"/usr/local/apache2"}
ARG SERVER_NAME
ENV SERVER_NAME=${SERVER_NAME:-"acake2php.local"}
ARG HTTP_PORT
ENV HTTP_PORT=${HTTP_PORT:-80}
ARG SSL_PORT
ENV SSL_PORT=${SSL_PORT:-443}
ARG USER
ENV USER=${USER:-acake2php}
ARG GROUP
ENV GROUP=${GROUP:-acake2php}
ARG PUID
ENV PUID=${PUID:-1000}
ARG GUID
ENV GUID=${GUID:-1000}

# add dedicated user
RUN addgroup -g $GUID $GROUP \
    && adduser -h $PWD -G $GROUP -D -u $PUID $USER \
    && sed -i -E -e "#User#s#www-data#$USER#g" \
       -e "#Group#s#www-data#$GROUP#g" "${SERVER_ROOT}/conf/httpd.conf"

# Copy application files
COPY --chown=$USER:$GROUP . .

# Set up Apache configuration
RUN envsubst < etc/apache2/conf-available/servername.conf > ${SERVER_ROOT}/conf/extra/servername.conf \
    && envsubst < etc/apache2/conf-available/ssl.conf > ${SERVER_ROOT}/conf/extra/ssl.conf \
    && envsubst < etc/apache2/sites-available/000-default.conf > ${SERVER_ROOT}/conf/extra/000-default.conf \
    && envsubst < etc/apache2/sites-available/001-ssl.conf > ${SERVER_ROOT}/conf/extra/001-ssl.conf \
    && echo "Include conf/extra/servername.conf" >> ${SERVER_ROOT}/conf/httpd.conf \
    && echo "Include conf/extra/ssl.conf" >> ${SERVER_ROOT}/conf/httpd.conf \
    && echo "Include conf/extra/000-default.conf" >> ${SERVER_ROOT}/conf/httpd.conf \
    && echo "Include conf/extra/001-ssl.conf" >> ${SERVER_ROOT}/conf/httpd.conf


# Expose Apache ports
EXPOSE ${HTTP_PORT} ${SSL_PORT}

# Enable Apache modules and start the server
RUN chmod +x Scripts/*.sh \
    && Scripts/a2enmod.sh

CMD ["apachectl", "-D", "FOREGROUND"]

