FROM httpd:2.4-alpine3.22

# Set up working directory and environment
ARG HTDOCS
ENV HTDOCS=${HTDOCS:-"/usr/local/apache2/htdocs"}
WORKDIR ${HTDOCS}

# Install base packages
RUN apk add --no-cache \
    bash gettext apache2 apache2-ctl apache2-ssl curl git \
    && ln -sf /dev/stdout /var/log/apache2/access.log \
    && ln -sf /dev/stderr /var/log/apache2/error.log

# Copy application files
COPY . .

# Set up Apache configuration
RUN mkdir -p /etc/apache2/sites-available \
    && envsubst < etc/apache2/sites-available/000-default.conf > /etc/apache2/sites-available/000-default.conf \
    && envsubst < etc/apache2/sites-available/001-ssl.conf > /etc/apache2/sites-available/001-ssl.conf

# Expose Apache ports
EXPOSE 80 443

# Enable Apache modules and start the server
RUN a2enmod proxy \
    && a2enmod proxy_fcgi \
    && a2enconf servername \
    && a2ensite 000-default \
    && a2ensite 001-ssl \
    && a2enmod mpm_event_module
ENTRYPOINT ["apachectl", "-D", "FOREGROUND"]
