version: 2
orbs:
#  node: circleci/node@3.0.0
jobs:
  build:
    docker:
    - image: betothreeprod/dind-php7
    - image: betothreeprod/mariadb-intel-nuc
      environment:
        PUID: 0
        PGID: 0
        TZ: Europe/Paris
        MYSQL_ROOT_PASSWORD: mariadb
        MYSQL_HOST: localhost
        MYSQL_DATABASE: aria_db
        MYSQL_USER: maria
        MYSQL_PASSWORD: maria-abc
    shell: /bin/bash -leo pipefail
    environment:
    - BASH_ENV: /etc/profile
    - DKR_ARCH: x86_64
    - MYSQL_HOST: 127.0.0.1
    - MYSQL_TCP_PORT: 3306
    working_directory: /var/www/html/
    steps:
    - checkout
    - run:
        command: git submodule sync
    - run:
        command: git submodule update --init --recursive
    # - node/install:
        # install-npm: true
    - restore_cache:
        key: v1-dependencies-{{ checksum "package-lock.json" }}
    - restore_cache:
        key: v1-dependencies-{{ checksum "composer.lock" }}
    - setup_remote_docker:
        docker_layer_caching: false
    - run:
        name: Install dependencies
        command: |
          apk update \
            && apk add \
              nodejs \
              npm \
              php7-session \
              mariadb-connector-c \
            && apk del build-base \
            && rm -rf /var/cache/apk/*
          npm install
    - run:
        name: Set architecture and Setup Environment Variables
        command: |
          balena_deploy $DKR_ARCH --nobuild --exit
    - run:
        name: Waiting for Mysql to be ready
        command: |
          set -x
          for i in `seq 1 10`;
          do
            nc -z $MYSQL_HOST $MYSQL_TCP_PORT && echo Success && exit 0
            echo -n .
            sleep 1
          done
          echo 'Failed waiting for Mysql' && exit 1
    - run:
        command: |
          set -x
          mkdir -p ./app/build/logs
          mkdir -p ~/phpunit
          source ./test-cake.sh --circle
          cat $MYPHPCMS_DIR/e13/etc/constantes.properties | grep PASSWORD_ADMIN | head -c 18
        when: always
    - save_cache:
        key: v1-dependencies-{{ checksum "composer.lock" }}
        paths:
        - app/Vendor
    - save_cache:
        key: v1-dependencies-{{ checksum "package-lock.json" }}
        paths:
        - node_modules
    - persist_to_workspace:
        root: .
        paths:
        - node_modules
        - app/Config
        - app/webroot
        - app/Vendor
  compose:
    docker:
    - image: betothreeprod/dind-php7
    shell: /bin/bash -leo pipefail
    environment:
    - BASH_ENV: /etc/profile
    - DKR_ARCH: x86_64
    steps:
    - checkout
    - run:
        command: git submodule sync
    - run:
        command: git submodule update --init --recursive
    - attach_workspace:
        at: .
    - setup_remote_docker:
        docker_layer_caching: false
    - run:
        name: Set architecture and Setup Environment Variables
        command: |
          source ./deploy.sh $DKR_ARCH --nobuild --exit
    - run:
        command: |
          set -u
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker-compose -f docker-compose.$DKR_ARCH build
    - store_test_results:
        path: ~/phpunit
    - store_artifacts:
        path: ~/phpunit
workflows:
  build-and-compose:
    jobs:
    - build
    - compose:
        requires:
        - build
        context: Info-b23prodtm
  version: 2
