version: 2.1
orbs:
  shellcheck: circleci/shellcheck@1.3.16
  kubernetes: circleci/kubernetes@2.0.2
jobs:  
  httpd:
    # The resource_class feature allows configuring CPU and RAM resources for each job. Different resource classes are available for different executors. https://circleci.com/docs/2.0/configuration-reference/#resourceclass
    resource_class: b23prodtm/linux
    docker:
      - image: cimg/base:2025.11               
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
    environment:
      TAG: latest-x86_64
      IMAGE: httpd
      BUILD_ARCH: x86_64
      WORK_DIR: deployment/images/httpd
    steps:
      - checkout
      #- setup_remote_docker:
      #    docker_layer_caching: true
      - run:
          name: Build Docker image with BUILDKIT (Docker Rootless)
          command: |
            cd $WORK_DIR
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker buildx build --push -t $DOCKER_USER/$IMAGE:$TAG -f Dockerfile.$BUILD_ARCH .
  mysql:
    # The resource_class feature allows configuring CPU and RAM resources for each job. Different resource classes are available for different executors. https://circleci.com/docs/2.0/configuration-reference/#resourceclass
    resource_class: b23prodtm/linux
    docker:
     - image: cimg/base:2025.11       
       auth:
         username: $DOCKER_USER
         password: $DOCKER_PASS
    environment:
      TAG: latest-x86_64
      IMAGE: mariadb
      BUILD_ARCH: x86_64
      WORK_DIR: deployment/images/mysqldb
    steps:
      - checkout
      #- setup_remote_docker:
      #    version: edge
      #    docker_layer_caching: false
      - run:
          name: Build Docker image with BUILDKIT (Docker Rootless)
          command: |
            cd $WORK_DIR
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker buildx build --push -t $DOCKER_USER/$IMAGE:$TAG -f Dockerfile.$BUILD_ARCH .
  php-fpm:
    # The resource_class feature allows configuring CPU and RAM resources for each job. Different resource classes are available for different executors. https://circleci.com/docs/2.0/configuration-reference/#resourceclass
    resource_class: b23prodtm/linux
    docker:
      - image: cimg/base:2025.11       
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
    environment:
      TAG: latest-x86_64
      IMAGE: php-fpm
      BUILD_ARCH: x86_64
      WORK_DIR: .
    steps:
      - checkout
      #- setup_remote_docker:
      #    version: edge
      #    docker_layer_caching: false
      - kubernetes/install_kubectl
      - run:
          name: Build Docker image with BUILDKIT (Docker Rootless)
          command: |
            cd $WORK_DIR
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker buildx create --driver kubernetes --use
            docker buildx ls
            docker buildx build --push -t $DOCKER_USER/$IMAGE:$TAG -f Dockerfile.$BUILD_ARCH .
  compose:
    # The resource_class feature allows configuring CPU and RAM resources for each job. Different resource classes are available for different executors. https://circleci.com/docs/2.0/configuration-reference/#resourceclass
    resource_class: b23prodtm/linux
    docker:
        - image: cimg/aws:2025.01
    shell: /bin/bash -leo pipefail
    environment:
        BASH_ENV: /etc/profile
        BUILD_ARCH: x86_64
    steps:
      - checkout
      #- setup_remote_docker:
      #    version: edge
      #    docker_layer_caching: true
      - run:
          command: |
            set -u
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker compose -f docker-compose.$BUILD_ARCH build
workflows:
  cleanup:
    jobs:
      - shellcheck/check:
          ignore: 'SC2154,SC1091,SC2034,SC2096,SC2038'
  build-and-compose:
    jobs:
      - httpd
      - mysql
      - php-fpm
      - compose:
          requires:
            - httpd
            - mysql
            - php-fpm
  version: 2
