#!/bin/sh

# When you send a docker stop command to your container,
# the myapp service will be killed and this script will be run;
# it will write either myapp's exit code (if myapp catches the TERM signal)
# or 130 (if myapp does not catch the TERM signal)
# to the special /run/s6-linux-init-container-results/exitcode file,
# which will be read by s6-overlay at the end of the container shutdown procedure,
# and your container will exit with that value.

if test "$1" -eq 256 ; then
  e=$((128 + $2))
else
  e="$1"
fi

echo "$e" > /run/s6-linux-init-container-results/exitcode
