;# =========================================================
;# Fichiers de configuration de pohse PHP-CMS :
;# SITEMAP.PROPERTIES _ MENU.PROPERTIES _ CONTENT-LANG.PROPERTIES _
;# CONSTANTES.PROPERTIES _ include/PHP_INDEX.INC.PHP::__construct()
;# ! VARIABLES $GLOBALS !
;# =========================================================
;# CE FICHIER supporte les variables environment en dollar et crochets {MA_VAR_ENV}.
;#

SERVEUR={{DB}_HOST}
BASE={MYSQL_DATABASE}
PORT={{DB}_TCP_PORT}
CLIENT={DATABASE_USER}
CLIENT_MDP={MYSQL_ROOT_PASSWORD}

;# Differencier les variables de test/local en la configuration de production
TEST_SERVEUR={{DB}_HOST}
TEST_BASE={TEST_DATABASE_NAME}
TEST_PORT={{DB}_TCP_PORT}
TEST_CLIENT={MYSQL_USER}
TEST_CLIENT_MDP={MYSQL_PASSWORD}

;# etc/getHashPassword.php
ADMIN="staff"
PASSWORD_ADMIN={MASTER_PASSWORD_HASH}
;# encoding
MYENCODING=ISO-8859-15
;# Contraindre dimensions Image affichee dans les posts
IMAGE_MAX_LARG=300
IMAGE_MAX_HAUT=300
