FROM balenalib/%%BALENA_MACHINE_NAME%%-alpine-node:18-3.18

RUN apk update \
        && apk add \
    mariadb-client \
    && apk del build-base \
    && rm -rf /var/cache/apk/*

# Enable udev for detection of dynamically plugged devices
ENV UDEV=on
COPY udev/usb.rules /etc/udev/rules.d/usb.rules

# Install dependencies
RUN install_packages findmnt util-linux grep

WORKDIR /usr/src
COPY scripts scripts
RUN chmod +x scripts/*

# Change your CMD as needed
CMD [ "/bin/bash", "/usr/src/scripts/idle.sh" ]
