FROM balenalib/%%BALENA_MACHINE_NAME%%-alpine-node

# requires node 20
#RUN yarn add balena-cli

# Enable udev for detection of dynamically plugged devices
ENV UDEV=on
COPY udev/usb.rules /etc/udev/rules.d/usb.rules

# Install dependencies
RUN install_packages findmnt util-linux grep \
     mariadb-client

WORKDIR /usr/src
COPY scripts scripts
RUN chmod +x scripts/*

# Change your CMD as needed
CMD [ "/bin/bash", "/usr/src/scripts/idle.sh" ]
