## No longer needed
#RewriteCond %{REQUEST_FILENAME} !-f
#RewriteRule ^ /index.php [L]
<Directory "/">
    AllowOverride All
    Require all denied
</Directory>
<VirtualHost *:${HTTP_PORT}>
    DocumentRoot ${HTDOCS}
    ServerAdmin webmaster@${SERVER_NAME}
    ServerName ${SERVER_NAME}
    ServerAlias www.${SERVER_NAME}
    <Directory "${WWW}">
        DirectoryIndex index.php
        Options +FollowSymLinks
        AllowOverride FileInfo
        Require all granted
        FallbackResource /index.php
    </Directory>
    ProxyPassMatch ^/(.*\.php(/.*)?)$ fcgi://127.0.0.1:9001/${HTDOCS}/$1
</VirtualHost>
