## No longer needed
#RewriteCond %{REQUEST_FILENAME} !-f
#RewriteRule ^ /index.php [L]
<VirtualHost ${SSL_PORT}>
    DocumentRoot ${HTDOCS}
    ServerAdmin webmaster@${SERVER_NAME}
    ServerName ${SERVER_NAME}:${SSL_PORT}
    ServerAlias www.${SERVER_NAME}:${SSL_PORT}
    <Directory \"${HTDOCS}\">
        DirectoryIndex index.php
        Options +FollowSymLinks
        AllowOverride FileInfo
        Require all granted
        FallbackResource /index.php
    </Directory>
    ProxyPassMatch ^/(.*\.php(/.*)?)$ fcgi://127.0.0.1:9002/${HTDOCS}/$1
    SSLEngine on
    SSLCertificateFile /etc/ssl/apache2/server.pem
    SSLCertificateKeyFile /etc/ssl/apache2/server.key
    #SSLCertificateChainFile /etc/ssl/apache2/server-ca.pem
    #SSLCACertificatePath /etc/ssl/apache2/ssl.crt
    #SSLCACertificateFile /etc/ssl/apache2/ssl.crt/ca-bundle.pem
</VirtualHost>
