name: Multi-Arch Build

on:
  push:
    branches: [ "main", "development" ]
  pull_request:

env:
  DOCKER_ORG: ${{ secrets.DOCKER_USER }}

jobs:
  build-services:
    runs-on: self-hosted
    #runs-on: ubuntu-latest
    environment: AUTH

    strategy:
      fail-fast: false
      matrix:
        arch: [ x86_64, aarch64, armhf ]

    steps:
      - uses: actions/checkout@v4

      - name: Enable QEMU
        uses: docker/setup-qemu-action@v3

      - name: Enable Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Sanitize ref name for Docker tag
        id: sanitize
        run: |
          RAW="${{ github.ref_name }}"
          # lowercase
          TAG=$(echo "$RAW" | tr '[:upper:]' '[:lower:]')
          # replace invalid chars with '-'
          TAG=$(echo "$TAG" | sed 's/[^a-z0-9._-]/-/g')
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      # Install Docker Compose v2 plugin
      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1
        with:
          version: latest   # or a specific version like v2.27.0

      - name: Build docker-compose stack
        env:
          BALENA_ARCH: ${{ matrix.arch }}
          BAKE_TAG: ${{ steps.sanitize.outputs.tag }}
        run: |
	  case "${BALENA_ARCH}" in
            "armhf")
              export PLATFORM="linux/arm/v7"
              ;;
            "aarch64")
              export PLATFORM="linux/arm64"
              ;;
            "x86_64")
              export PLATFORM="linux/amd64"
              ;;
            *)
              export PLATFORM="linux/$(uname -m)"
	      ;;
          esac
          docker buildx bake -f docker-bake.hcl --set "*.platform=${PLATFORM}"
          docker compose up -d
